[Build] Fix `die++` link libraries  (#5)
# Description

CMake target `die++` was collecting all linked libraries specified by
`die`, including those that were not found. As a consequence if the
system building `die` didn't have the Qt5 libraries, the build would
fail even though those libs are not needed with the following error

```text
$ cargo build -vv
[...]
  --- stderr
  /home/chris/.cargo/git/checkouts/die-rust-16d54ce51808913d/0e11039/libdie++/build/_deps/dielibrary-src/dep/XCapstone/x86
  /home/chris/.cargo/git/checkouts/die-rust-16d54ce51808913d/0e11039/libdie++/build/_deps/dielibrary-src/src/lib
  CMake Error at CMakeLists.txt:60 (target_link_libraries):
    Target "die++" links to:

      Qt5::Core

    but the target was not found.  Possible reasons include:

      * There is a typo in the target name.
      * A find_package call is missing for an IMPORTED target.
      * An ALIAS target is missing.



  CMake Generate step failed.  Build files cannot be regenerated correctly.
  thread 'main' panicked at /home/chris/.cargo/git/checkouts/die-rust-16d54ce51808913d/0e11039/build.rs:21:9:
  assertion failed: std::process::Command::new("cmake").current_dir(BASE_DIR).args(["-S",
                                      "."]).args(["-B",
                                  "build"]).spawn().unwrap().wait().expect("failed to configure cmake").success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

This PR fixes this behavior by only requiring to link `die++` with the
libraries required.

The PR also documents better how to install the `die-rust` library in
the README.